from math import radians

# Экран и арена
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
FPS = 60
ARENA_MARGIN = 50  # Отступ арены от краёв окна
BACKGROUND_COLOR = (18, 18, 22)
ARENA_COLOR = (35, 35, 42)
ARENA_BORDER_COLOR = (90, 90, 105)
ARENA_BORDER_WIDTH = 4
FIXED_DT = 1/60.0
MAX_FRAME_DT = 0.25  # максимальный dt для предотвращения "телепортации"


# Игрок
PLAYER_SIZE = 32
PLAYER_COLOR = (245, 245, 245)
PLAYER_START_POS = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
PLAYER_MAX_SPEED = 420.0
PLAYER_ACCELERATION = 2000.0
PLAYER_DECELERATION = 2500.0
PLAYER_MAX_HP = 100
PLAYER_DAMAGE_PER_HIT = 20          # 5 ударов до смерти — не ваншот
PLAYER_INVULNERABILITY_DURATION = 0.8  # i-frames после удара
PLAYER_BLINK_FREQ = 20.0
PLAYER_FACE_EYE_OFFSET_X = 2
PLAYER_FACE_EYE_OFFSET_Y_TOP = -5
PLAYER_FACE_EYE_OFFSET_Y_BOTTOM = 2
PLAYER_FACE_EYE_WIDTH = 8
PLAYER_FACE_EYE_HEIGHT = 4

# вражина миньон
MINION_RADIUS = 15
MINION_COLOR = (0, 100, 255)
MINION_MAX_SPEED = 600
MINION_ACCELERATION = 500
MINION_SEPARATION_DISTANCE = 50.0
MINION_MAX_FORCE = 3000.0
MINION_MAX_HP = 30

# сетка
SG_CELL_SIZE = 60

# светик
AMBIENT_COLOR = (0, 0, 0)
LIGHT_COLOR = (255, 255, 255)
LIGHT_RADIUS = 800
LIGHT_ANGLE_EUL = 120
LIGHT_ANGLE_RAD = radians(LIGHT_ANGLE_EUL / 2)
GLOBAL_LIGHT_INTENSITY = 180
DAMAGE_FLASH_DURATION = 0.5
DAMAGE_FLASH_INTENSITY = 140

# готовьте пушки
MINIGUN_FIRE_RATE = 16.0  # выстрелов в секунду
MINIGUN_PROJECTILE_SPEED = 1400.0
MINIGUN_DAMAGE = 12
MINIGUN_SPREAD = 0.07  # в радианах
MINIGUN_PROJECTILES_PER_SHOT = 1
MINIGUN_LIFETIME = 1.2
MINIGUN_IS_AUTOMATIC = True
MINIGUN_COLOR = (255, 220, 80)
MINIGUN_MUZZLE_RADIUS = 140
MINIGUN_MUZZLE_LIFETIME = 0.04

SHOTGUN_FIRE_RATE = 1.8
SHOTGUN_PROJECTILE_SPEED = 1100.0
SHOTGUN_DAMAGE = 14
SHOTGUN_SPREAD = 0.28
SHOTGUN_PROJECTILES_PER_SHOT = 7
SHOTGUN_LIFETIME = 0.7
SHOTGUN_IS_AUTOMATIC = False
SHOTGUN_COLOR = (255, 120, 60)
SHOTGUN_MUZZLE_RADIUS = 260
SHOTGUN_MUZZLE_LIFETIME = 0.08

WEAPON_MUZZLE_OFFSET = 22.0  # смещение дула от центра игрока

# снаряды
PROJECTILE_POOL_SIZE = 600
PROJECTILE_RADIUS = 8

# UI
HUD_COLOR = (240, 240, 240)
HUD_HEART_COLOR = (220, 50, 60)
HUD_HEART_SIZE = 32
HUD_FONT_SIZE = 28
HUD_PADDING = 20

# спавнер
WAVE_SPAWNER_INITIAL_INTERVAL = 4.0
WAVE_SPAWNER_MIN_INTERVAL = 2.0
WAVE_SPAWNER_INTERVAL_DECAY = 0.15
WAVE_SPAWNER_BASE_COUNT = 3
WAVE_SPAWNER_COUNT_GROWTH = 2
WAVE_SPAWNER_MAX_COUNT = 40
WAVE_SPAWNER_SPAWN_MARGIN = 20.0
