# Generated by Django 5.2.12 on 2026-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('sender', models.TextField(verbose_name='Отправитель')),
                ('recipient', models.TextField(verbose_name='Получатель')),
            ],
        ),
    ]
