# Generated by Django 5.2.12 on 2026-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent_by_you',
            field=models.BooleanField(default=False, verbose_name='Отправлено вами'),
        ),
    ]
