# Generated by Django 5.2.12 on 2026-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_email_sent_by_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='email',
            name='trashed',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
