# Generated by Django 5.2.12 on 2026-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_email_archived_email_trashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название папки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sent_by_you',
        ),
        migrations.RemoveField(
            model_name='email',
            name='trashed',
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='email',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='emails', to='pages.folder', verbose_name='Папки'),
        ),
    ]
